### ISSUE TITLE
Make gerl into a behavior

### ISSUE THREAD

**Issue by dbravender** [dbravender/gerl#3]
A behavior is basically just a compile time check to ensure that certain functions are defined in a module. Having gerl be a behavior might give more obvious compile-time errors.

**Comment by robertdfrench** [comment]
Is this somewhat similar to an interface in Objective-C or Java? Kindof like an agreement that a module makes to implement certain functions in certain ways?

**Comment by dbravender** [comment]
Yes, it's similar. An Erlang behaviour is dead simple to write. You just write the function signatures that must be implemented. Implemented in commit dbravender/gerl@c5bcef797ab373bd94bf1bef28798d71d9a98e1e
